### PR TITLE
Fix #29

### LINKED ISSUE #29: Whats about SEO?
http://webcache.googleusercontent.com/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=cache%3Ahttps%3A%2F%2Fshop.polymer-project.org&oq=cache%3Ahttps%3A%2F%2Fshop.polymer-project.org&rlz=1C1RAEH_deDE626DE648&aqs=chrome..69i57j69i58.1255j0j4

I Think it is bad for a Web-Shop.

### PR DESCRIPTION
**Pull request by blasten**

### CODE REVIEW

**Comment by frankiefu** [comment]
LGTM

**Comment by abdonrd** [comment]
@blasten @frankiefu Did you deploy it? I always have the same title if I share shop links in social networks.

**Comment by blasten** [comment]
I don't think that it will fix the issue when sharing a link though. Facebook and Twitter bots only look for static `meta` elements in the markup. e.g. https://developers.facebook.com/docs/sharing/webmasters

**Comment by abdonrd** [comment]
@frankiefu thanks!

@blasten but if you don't have the meta og, they get the title.
I already report at new docs site too: https://github.com/Polymer/docs/issues/1632

I think that is a very very important thing.

**Comment by blasten** [comment]
@abdonrd but it has to be static I think. I don't think they run a browser in the server to extract the meta data.

**Comment by abdonrd** [comment]
@blasten probably you are right. 😕 

Do you plan any solution?

**Comment by blasten** [comment]
@abdonrd the solution would require server-side support, potentially the server could detect the user agent and if it's `facebot`, for example, then it can inject the `<meta>` elements. Unfortunately, this is a little bit out of scope for now.

**Pull request merged**
