### PR TITLE
feat(shop-app.html): modify the message for the aria live region

### PR DESCRIPTION
**Pull request by felixzapata**
Hi today is the Global Accessibility Awareness Day :) so I propose this small change to improve the message when the section has changed.

By the way and just for curiosity, I think there is a bug with Voice Over and Firefox because I can´t receive the information from the aria region.

### CODE REVIEW

**Comment by blasten** [comment]
I'm okay with this change although I think that it might be too verbose. @robdodson wdyt?

**Comment by robdodson** [comment]
I think it's fine to add more info if it's beneficial. Curious what @alice thinks

**Comment by blasten** [comment]
okay :shipit:

**Comment by felixzapata** [comment]
hi, "my two cents" (like Kent Brockman).. I think this small change has two benefits:

1. advise the user what happen ("the page / section has changed")
2. inform the user where is now

Only with the title of the page I think can be confuse because for example, when the user clicks in one of the main tabs, the screen reader only says the title of the page filled in the aria region (you use this region in a way to inform the user what is happening), but the user does not know what has happened: "Am I in another section? Are the content different?"

**Comment by alice** [comment]
The benefit of the current string is that it gets the most important information (where am I?) to the user immediately - imagine someone on a 20 cell braille display getting this notification. I wonder if something like
```js
this._announce(detail.title + ', loaded');
```
would be the best of both worlds? What is announced on "actual" page loads?

**Comment by blasten** [comment]
@alice I like it! 
If you guys have no objections, @felixzapata would you mind updating the PR?

**Comment by frankiefu** [comment]
@blasten already fixed that in here: https://github.com/Polymer/shop/pull/32/commits/ccba9f4b0675760b2afa07895f5a50f34de8d9fc

**Comment by felixzapata** [comment]
so, is already it not necessary to update the PR?

**Comment by frankiefu** [comment]
@felixzapata Yeah, no need to update this PR.  Thanks!

**Pull request closed without merging**
