### PR TITLE
Credential payment api

### PR DESCRIPTION
**Pull request by spyhole**
why not?

### CODE REVIEW

**Comment by spyhole** [comment]
https://cla.developers.google.com/ to signed.

**Comment by spyhole** [comment]
WARNING!!!!!!!!!!!!!!!
@frankiefu @keanulee 你们俩这二货，不把冲突解决了提交，我等你们变相其实中国华为人！！和孟晚舟一样！！，我是一个曾经近7年的华为人！！
https://www.linkedin.com/in/singerswang/

**Comment by spyhole** [comment]
if @frankiefu @keanulee you two Gods, bring firebase , or shut up!

**Comment by keanulee** [comment]
Not interested in having these changes in the main `master` branch, but will keep the [`credential-payment-api`](https://github.com/Polymer/shop/compare/credential-payment-api) branch around so users can see the changes required (see my opinion at https://github.com/Polymer/shop/pull/91#issuecomment-331957032).

**Comment by spyhole** [comment]
I will implement it in a real-life example of SHOP.  :.-(

**Pull request closed without merging**
