### PR TITLE
Replace iron-localstorage with app-localstorage-document

### PR DESCRIPTION
**Pull request by keanulee**

### CODE REVIEW

**Comment by frankiefu** [comment]
Reloading the app seems to clear the cart data.

**Comment by frankiefu** [comment]
Sorry, stupid user error, my bad. It's working perfectly.  LGTM

**Comment by ptamarit** [comment]
Hi @keanulee & @frankiefu,

It's probably a dumb question, but why did you migrate from `iron-localstorage` to `app-localstorage-document`?
Both are official elements and I didn't find anywhere what are the differences between them.

Cheers,
Pablo

**Comment by Boscop** [comment]
@ptamarit I'm wondering the same.

**Comment by keanulee** [comment]
One difference is that `app-localstorage-document` coordinates across instances within the same page, but the bigger picture is that the `app-storage` set of elements are newer and are designed to be able to use other storage providers (e.g. firebase), though we don't use that here.

**Pull request merged**
